# branches to build
branches:
  # whitelist
  only:
    - master
    - production

# Build worker image (VM template)
image: Visual Studio 2019


# build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3
  - '%USERPROFILE%\.nuget\packages'


# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to
                                  # account/project feeds for pull request builds

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: 
  - Release

init:
- ps: $env:LABEL = "-CI" + $env:APPVEYOR_BUILD_NUMBER.PadLeft(6, "0")
- cmd: echo LABEL %LABEL%

before_build:
  - cmd: dotnet --version
  - dotnet restore --verbosity minimal

build_script:
  - dotnet build -c %CONFIGURATION% --no-restore --version-suffix %LABEL%

after_build:
  - dotnet pack "FastDictionaryComparer" --no-build --version-suffix %LABEL% -o artifacts

before_test:
  - echo "Running Tests"
test_script:
  - dotnet test "FastDictionaryComparer.Test" -c %CONFIGURATION%


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: .\**\artifacts\**\*.*

deploy:
    # Deploying to NuGet feed
  - provider: NuGet
    api_key:
      secure: 02X7mXNXhf1D/vOk9tyJmjcUVrGXBbAHdxkUDLXP0BHxeuH7LDTLgFrBrZsPYft7
    skip_symbols: false
    symbol_server:
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true

    # Deploy to GitHub Releases
  - provider: GitHub
    artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true       # deploy on tag push only

# scripts to run before deployment
before_deploy:

# scripts to run after deployment
after_deploy:

# to run your custom scripts instead of provider deployments
deploy_script: